services:
  postgres:
    image: postgres:16
    container_name: shorter_postgres
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}" ]
      interval: 3s
      timeout: 5s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: shorter_migrate
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}?sslmode=disable",
        "up"
      ]

  shorter:
    image: shorter-app:latest
    container_name: shorter_app
    restart: unless-stopped
    depends_on:
      - postgres
      - migrate
    env_file:
      - .env.prod
    environment:
      SHORTER_LISTEN_PORT: ${SHORTER_LISTEN_PORT}
      SHORTER_NODE_ID: ${SHORTER_NODE_ID}
      SHORTER_BASE_URL: ${SHORTER_BASE_URL}

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "${SHORTER_LISTEN_PORT}:${SHORTER_LISTEN_PORT}"

volumes:
  postgres_data: